/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BeauTime: typeof import('./components/beauTime.vue')['default']
    Biaoge: typeof import('./components/biaoge.vue')['default']
    Cards: typeof import('./components/cards.vue')['default']
    GaodeMap: typeof import('./components/gaodeMap.vue')['default']
    HomeHeader: typeof import('./components/homeHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TqEcharts: typeof import('./components/yuliu/tqEcharts.vue')['default']
    TqTable: typeof import('./components/yuliu/tqTable.vue')['default']
    Tubiao: typeof import('./components/tubiao.vue')['default']
  }
}
